### ISSUE TITLE
Scraping Likes, but no reactions

### ISSUE THREAD

**Issue by MariuszSiatka** [kevinzg/facebook-scraper#46] opened 2020-03-09 19:04 UTC
I have noticed, that your script only scraps total number of likes and it dose not take reactions at all

Also shares are not working at all

**Comment by kevinzg** [comment] 2020-03-12 01:04
Yes, the mobile version of Facebook doesn't reactions so they are not being scraped.

Closing this as duplicate of #39 and #1.

**Closed by kevinzg** 2020-03-12 01:04 UTC
