### ISSUE TITLE
Issue #544 was closed accidently. 

### ISSUE THREAD

**Issue by usman87626** [kevinzg/facebook-scraper#545] opened 2021-11-05 14:39 UTC
[hashdevelop2k20.zip](https://github.com/kevinzg/facebook-scraper/files/7486751/hashdevelop2k20.zip)
Here is my HTML FILE

**Comment by usman87626** [comment] 2021-11-05 21:37
@neon-ninja Can you please have a look at html file? Old issue was closed accidently while closing the comment tab

**Comment by neon-ninja** [comment] 2021-11-05 21:57
You can reopen an issue. I'll take a look on Monday

**Comment by usman87626** [comment] 2021-11-05 23:18
Sure

**Comment by neon-ninja** [comment] 2021-11-07 20:43
Duplicate of https://github.com/kevinzg/facebook-scraper/issues/544

**Closed** 2021-11-07 20:43 UTC
