### ISSUE TITLE
About temporary ban on extracting comments

### ISSUE THREAD

**Issue by cmhcheung** [kevinzg/facebook-scraper#281] opened 2021-05-22 12:33 UTC
I got an exception - Exception while extracting comments: TemporarilyBanned('You’re Temporarily Blocked') and grateful for any help to solve the problem.
1. Is there a way to specify the proxy servers like the way I specify cookies='cookies.txt'?
2. Is there a way to know if my temporary ban has been lifted?
3. What is the suggested frequency and pages for web scraping?  In my case, I would like to scrape a site for comments every hour with the default pages parameter = 10, is it too much?

**Comment by neon-ninja** [comment] 2021-05-22 20:33
Yes, you can use the `set_proxy` function. Temporary blocks seem to resolve within about an hour. It depends how many comments the average post has. If you're regularly getting temp banned, you should probably scrape slower or less.

**Comment by cmhcheung** [comment] 2021-05-23 04:15
Thanks a lot!

**Comment by enaserianhanzaei** [comment] 2021-05-25 18:59
@cmhcheung 

Could you explain how you worked it out, the proxy setting?

I added this two lines of code to facebook_scraper/__init__.py    :

 proxy = kwargs.pop('proxy', None)
 set_proxy(proxy)

but I'm getting this error 

HTTPConnectionPool(host='5.210.129.98', port=8080): Max retries exceeded with url: http://ifconfig.co/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbeb7f14e48>, 'Connection to 5.210.129.98 timed out. (connect timeout=5)'))

**Comment by neon-ninja** [comment] 2021-05-25 23:18
This proxy doesn't work, `curl -vv -x 5.210.129.98:8080 ipinfo.io` times out too. Shouldn't be any need to edit init.py, you should be able to do `from facebook_scraper import set_proxy`.

**Comment by enaserianhanzaei** [comment] 2021-05-26 13:51
Thanks @neon-ninja ,

I followed the steps you mentioned, with this proxy 77.68.29.157:80 (I checked it and it works), then I called the set_proxy function, and it's ok, but when it comes to get the fb url, I get this error:


HTTPSConnectionPool(host='m.facebook.com', port=443): Max retries exceeded with url: /86174496459/posts/10158500300251460 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Temporarily Unavailable',))) for this https://www.facebook.com/86174496459/posts/10158500300251460

**Comment by enaserianhanzaei** [comment] 2021-05-26 19:24
@neon-ninja 

I finally figured the proxy part out (I guess),

However, I noticed an error when you call a url with several images using proxy:

proxy: 79.143.87.117:9090
 url https://www.facebook.com/groups/1166154663436469/permalink/4206825836035988

there is an error in extractors.py , def extract_photo_link_HQ, where It returns no match (None). So I modified the image_regex a bit and now it works:

image_regex = re.compile(
    r'<a href=\"([^\"]+?)\" target=\"_blank\" class=\"sec\">([^\"]+?)<\/a>',
    re.IGNORECASE,
)

**Comment by neon-ninja** [comment] 2021-05-26 21:38
previously, this image_regex has looked for a link with the string "View Full Size". This wouldn't work if the page was served with a different language. However, as you've discovered, the view full size link is the only link on the page with class sec and target _blank, so that's enough for a unique match. Committed as https://github.com/kevinzg/facebook-scraper/commit/77c7fb6b2c1103affefbf9b690a13f48a53bd031

**Comment by maorkavod** [comment] 2021-06-03 10:58
@neon-ninja 
Hi,
i can i pass proxy & port with user & pass to the get_posts function? 

thank you!

**Comment by neon-ninja** [comment] 2021-06-03 11:00
Not currently, you'd need to use the `set_proxy` function

**Closed** 2021-06-16 08:10 UTC
Labels: enhancement, question
