### ISSUE TITLE
The code starts over after temporary ban

### ISSUE THREAD

**Issue by msaljoug** [kevinzg/facebook-scraper#638] opened 2022-01-19 22:22 UTC
I used #310 code example to help get around temporary ban, which causes disruptions when getting posts. However, it started scraping the page from the beginning rather than where I was interrupted (temporary ban). In other words, it seems  

```
start_url = None
def handle_pagination_url(url):
    global start_url
    start_url = url
for post in get_posts('TwiddyOuterBanks', 
                              page_limit = None,
                              request_url=start_url,
                              request_url_callback=handle_pagination_url,
                              cookies="cookies.json",
                              options={"comments": True,
                                       "reactors": True,
                                       "allow_extra_requests": True,
                                       "posts_per_page": 200}, 
                              extra_info = True)
```
does not work as they should.

**Comment by neon-ninja** [comment] 2022-01-19 22:49
Duplicate of https://github.com/kevinzg/facebook-scraper/issues/637

**Closed** 2022-01-22 19:05 UTC
