### ISSUE TITLE
I just start using this and I extract some data from a fb page pretty easy. The only problem I have is that I can only extract the likes and not the other reactions on a post

### ISSUE THREAD

**Issue by voinaandramaria** [kevinzg/facebook-scraper#21] opened 2019-12-22 21:11 UTC

**Comment by kevinzg** [comment] 2019-12-23 03:15
Yep, the scraper uses the mobile version of Facebook, and that version just has the Likes count, not the other reactions.

**Comment by kevinzg** [comment] 2020-03-12 01:04
Duplicate of #39

**Closed by kevinzg** 2020-03-12 01:04 UTC
