### ISSUE TITLE
Feature to extract post from a facebook story page rather than from account

### ISSUE THREAD

**Issue by STG284** [kevinzg/facebook-scraper#92] opened 2020-07-27 15:37 UTC
For example to extract from https://m.facebook.com/story.php?story_fbid=10165158992115725&id=153080620724 this page instead of scraping from DonaldTrump/posts

**Comment by neon-ninja** [comment] 2021-05-15 03:34
this is now possible as of https://github.com/kevinzg/facebook-scraper/pull/184

**Comment by neon-ninja** [comment] 2021-05-15 03:35
duplicate of https://github.com/kevinzg/facebook-scraper/issues/92

**Closed by neon-ninja** 2021-05-15 03:34 UTC
Labels: enhancement
